---
fileVersion: v1
instanceName: Greet

# Incoming request matching is done in the order of definition,
# sequentially, from the first one to the last one,
# once a match is found, the processing stops
calls:

# First, we try to match a call to john
- url: /SayHello
  method: post
  request:
    body:
      Name: "john"
  response:
    body:
      Message: Hello john!
    status: OK

# Then, we try to match a call to truong
- url: /SayHello
  method: post
  request:
    body:
      Name: truong
  response:
    body:
      Message: Hello truong!
    status: OK

# And if no match, fall back to NotFound
- url: /SayHello
  method: post
  # "request" section is optional and may be absent
  #   -  if "request" section is absent 
  #      then any call of the method is a match
  response:
    status: NOT_FOUND
